@DientesLimpios.API_HostAddress = http://localhost:5180/api/consultorios

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}\019cdc9a-348e-7933-9cc6-52e778b9007e
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Consultorio A"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019cdc9a-348e-7933-9cc6-52e778b9007e
Content-Type: application/json

{
  "nombre": "Consultorio B - Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}\019cdc9a-348e-7933-9cc6-52e778b9007e
Accept: application/json
